apiVersion: v1
kind: Service
metadata:
  name: demo-app
  annotations:
    metallb.universe.tf/address-pool: lecture
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 80